### ISSUE TITLE
Dead link SourceControl page

### ISSUE THREAD

**Issue by tdalon** [rubberduck-vba/RubberduckWeb#52]
In this page http://rubberduckvba.com/SourceControl
the link to the wiki page explaining the feature does not work.
---
I am interested to know what this features does / if it also export / extract the code to files.
Couldn't find any doc in the wiki about this neither.
Maybe shall be an issue for this: https://github.com/rubberduck-vba/Rubberduck/wiki

**Comment by bclothier** [comment]
@tdalon  we need to update the web page. The links are dead because we have discontinued the source integration. See [this closed issue in our Rubberduck repository](https://github.com/rubberduck-vba/Rubberduck/issues/3758). To use Rubberduck with your source control, you should use the Export functionality which is still available for easily importing / exporting files en masse and you would use the source control externally.

**Comment by retailcoder** [comment]
The website will be updated over the weekend with the release of v2.2 (needs the 2.2 build for the inspections page).

**Comment by retailcoder** [comment]
Essentially the feature provided a dockable panel similar to Visual Studio's *Team Explorer*, but it was hard-wired to work with git, and had a number of bugs that made it rather unstable and annoying. Since providing source control tooling is only marginally in-scope for Rubberduck, we chose to remove the buggy feature instead of devoting our limited time & resources to it. The feature might re-emerge at one point in the future, but for now it was interfering with the core stuff, so we're pulling it out.

You can try older versions (v2.1 still has it), but in any case nothing it does can't be done with *export all*, your favorite 3rd-party source control tool, and manually importing the remote changes (our *import* feature makes it easy to import multiple files at once).

**Comment by retailcoder** [comment]
Removed the page, updated website will be deployed once we have the final 2.2 build.
