### ISSUE TITLE
Does Rubberduck have a source control feature?

### ISSUE THREAD

**Issue by bsacheri** [rubberduck-vba/RubberduckWeb#53]
Google shows a link to this page but the page has errors.  
[rubberduckvba.com/SourceControl](url)

The cached version of this page is:
[http://webcache.googleusercontent.com/search?q=cache:oLO0Ksa1AkcJ:rubberduckvba.com/SourceControl+&cd=1&hl=en&ct=clnk&gl=us](http://webcache.googleusercontent.com/search?q=cache:oLO0Ksa1AkcJ:rubberduckvba.com/SourceControl+&cd=1&hl=en&ct=clnk&gl=us)

It's not clear to me if source control is a feature of the product for end users, or only showing how Rubberduck itself is maintained.

**Comment by bsacheri** [comment]
I was trying to captialize the title when I hit a key that made my browser open the post a new window, thus saving the post.  This is now a duplicate.  You can delete either #53 or #54.

**Comment by retailcoder** [comment]
An in-IDE integrated source control panel akin to Visual Studio's *Team Explorer* has been a wet dream since the project's beginning, and we were getting pretty close, however there were **a lot** of annoying issues and since Rubberduck is such a huge project and we are a relatively small team with limited time and resources, a decision was made to drop the feature, and [announced shortly before the 2.2 release](https://rubberduckvba.wordpress.com/2018/04/05/coming-soon-in-rubberduck-2-2/) on the *RD News* project blog and [the project's Twitter feed](https://twitter.com/@rubberduckvba).
