### ISSUE TITLE
Permanently redirect .html pages to mvc controllers

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/RubberduckWeb#7]
http://rubberduck-vba.com/news.html redirects to http://rubberduckvba.com/news.html, which results in a 404.

http://stackoverflow.com/q/16979234/3198973 should help us do that for all five of the old pages.
- [ ] Features.html => ~/Features/
- [ ] Home.html => ~/
- [ ] Contact.html => ~/Contact/
- [ ] About.html => ~/About/
- [ ] News.html => ~/News

**Comment by retailcoder** [comment]
FWIW I'm not going to be renewing the original rubberduck-vba.com domain when it expires in February.

**Comment by EBrown8534** [comment]
I think it's prudent just to close this, this cannot be resolved by the method posted by @ckuhn203 without making IIS configuration changes. (`.HTML` pages don't call the managed handlers in IIS, which means it just looks for that static page.) The best we could do is create an HTML page that contains the following:

    <meta http-equiv="refresh" content="0;URL='/newpage/'" />

But this would mean creating a `.html` page for each of the pages that need redirected, and would be ugly in our site root.

The next best thing would be to create a custom errors page that would be displayed for `404 Not Found` instead of the default which has information about the new links on it, but I'm not certain that even that would work with a `.html` page.
