### ISSUE TITLE
Home page returns error

### ISSUE THREAD

**Issue by sh67** [rubberduck-vba/RubberduckWeb#78]
When navigating to [rubberduckvba.com](rubberduckvba.com), the follow error is returned.

Error.
An error occurred while processing your request.

This occurs when using Chrome on Win 10 Enterprise with all extensions turned off. (Chrome 81.0.4044.129 (Official Build) (64-bit))
This also occurs with IE 11 (because company-provided machine).

**Comment by retailcoder** [comment]
Thanks for the heads-up, I'm aware of the situation and currently working (as time allows) on getting the GitHub-provided content back online. Thinking the API limits were busted because of how the download stats are compiled...
When the (full) site returns it'll be persisting that content to a database, and additional GitHub-provided content will be added (namely, example pages for Rubberduck annotations). Download stats will only show totals for the latest release and pre-release builds.

**Comment by sh67** [comment]
I appreciate the quick reply. And I apologize for filing a report for something which was a known issue. I realize no one needs additional reports for known issues, especially for something you're doing in your own spare time.

I'm going to close this. If it needs to remain open for some reason, please feel free to reopen it.

**Comment by retailcoder** [comment]
Nah it's fine - I should have made an issue for it anyway. I'll reopen this one and reference it when I create the PR.

**Comment by retailcoder** [comment]
Updated website is published - still missing screenshots, but no longer blowing up :)
